apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.12
          ports:
            - containerPort: 27017
