apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-rwm
  namespace: jenkins-ns
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-standard
